### ISSUE TITLE
Can I keep my semicolons untouched ?

### ISSUE THREAD

**Issue by moodymudskipper** [r-lib/styler#1017]
I'd like {styler} to not convert existing semicolons to new lines. 

This is different from #767 where OP wanted to add new semicolons.

Is this feasible with {styler} ?

**Comment by lorenzwalthert** [comment]
Yes, but not supported out of the box because the tidyverse style guide does not support this. You can create generate your own style guide and remove the rule that converts semi colons to line breaks. You can find instructions here: https://styler.r-lib.org/dev/articles/distribute_custom_style_guides.html

**Comment by lorenzwalthert** [comment]
Also, with `scope < "tokens"`, no tokens will be formatted, and hence `;` remains unchanged, as all other tokens such as in `x = 3`.

**Comment by moodymudskipper** [comment]
Amazing this is what I needed, thanks a lot!

``` r
styler::style_text("quote({1;2})", scope = "indention")
#> quote({1;2})
```

<sup>Created on 2022-10-01 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
