### ISSUE TITLE
Does  styler include a transformer that can replace T with TRUE and F with FALSE in R code?

### ISSUE THREAD

**Issue by vertesy** [r-lib/styler#1156]
1. Does  styler include a transformer that can replace T with TRUE and F with FALSE in R code?
2. Ideally it would be generic to so that I could also use it to replace shorthand e.g. `p0` > `paste0`
3. If none exists, is there simple transformer example that I could use to model on?

Thank you!

**Comment by lorenzwalthert** [comment]
it's generally unsafe to do that since you could have
```r
T <- 'hi there'
```
You needed advanced static code analysis tools to ensure you only convert a true `TRUE`. That's out of scope for {styler}. But {lintr} offers checks for that so you can fix it manually. 

Having said that, there are no generic transformers that replace arbitrary text and I would strongly advise against such replacements since they make styling unpredictable. Of course, you could write your own, there is [documentation](https://styler.r-lib.org/articles/customizing_styler.html) on that too.

**Comment by vertesy** [comment]
It looks a bit complicated to me, so I wont implement it via `styler`, but thank you for the explanation and warning. (Since the file is under git, I can see if something odd is replaced)

**Comment by vertesy** [comment]
Solved in `PackageTools`'s `replace_tf_with_true_false()`. Works completely safely with `strict = TRUE` (default).
