### ISSUE TITLE
Styling a call with a condition changes `=` by `<-`

### ISSUE THREAD

**Issue by olivroy** [r-lib/styler#1225]
This gets restyled.
```r
quiet <- FALSE
cli::cli_abort(c(
  if (quiet) "x" = "Don't show this",
  "Show that"
)
)
#> Error:
#> ! Show that
```

to 

```r
quiet <- FALSE
cli::cli_abort(c(
  if (quiet) "x" <- "Show this",
  "Show that"
))
```

Which seems incorrect? The restyled code doesn't work correctly with `quiet = TRUE`.

**Comment by IndrajeetPatil** [comment]
I don't see difference in their behaviour. What am I missing?

- `quiet <- FALSE`

``` r
quiet <- FALSE

cli::cli_abort(c(
  if (quiet) "x" = "Don't show this",
  "Show that"
))
#> Error:
#> ! Show that

cli::cli_abort(c(
  if (quiet) "x" <- "Don't show this",
  "Show that"
))
#> Error:
#> ! Show that
```

- `quiet <- TRUE`

```r
quiet <- TRUE

cli::cli_abort(c(
  if (quiet) "x" = "Don't show this",
  "Show that"
))
#> Error:
#> ! Don't show this
#> Show that

cli::cli_abort(c(
  if (quiet) "x" <- "Don't show this",
  "Show that"
))
#> Error:
#> ! Don't show this
#> Show that
```

<sup>Created on 2024-08-05 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by olivroy** [comment]
oh you are right, my code is invalid. it should probably be

```
cli_abort(c(
  x = if (quiet) "Don't show this",
  "show this"
))
```

(haven't tested it)

**Comment by MichaelChirico** [comment]
Note that in `c(if (quiet) x = 'a', 'b')`:

 - The name `x` is never part of the output from `c()` -- the output is totally unnamed (`is.null(names(.))`)
 - If `isTRUE(quiet)`, a variable `x` will be assigned to `'a'` in the calling environment. Otherwise, no such variable is created.

(that behavior is identical to `<-`)

In `c(x = if (quiet) 'a', 'b')`:

 - When `isTRUE(quiet)`, the output will have an element named `'x'`. The element `'b'` will always have name `''` (i.e., zero-length string).

I'm not sure what's intentional but there's some slight differences in implication.
