### ISSUE TITLE
Example in docs for style_file generates an error

### ISSUE THREAD

**Issue by joranE** [r-lib/styler#307]
When I run `style_file` the file appears to be styled correctly, but the function returns the following error instead of the promised data frame:

> Error: object ‘col_align’ is not exported by 'namespace:crayon'

It happens when I run it on my own files and when running the first example under `?style_file` in a clean R session. The error occurs with both the CRAN version and the dev version (which is the version running in the session info below).

My `sessionInfo`:

```
R version 3.4.3 (2017-11-30)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: OS X El Capitan 10.11.5

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] styler_1.0.9000

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.12     crayon_1.3.2     assertthat_0.2.0 digest_0.6.12    withr_2.1.1      enc_0.1         
 [7] R6_2.2.2         backports_1.1.2  git2r_0.19.0     magrittr_1.5     httr_1.3.1       rlang_0.1.6     
[13] curl_2.8.1       rstudioapi_0.6   devtools_1.13.3  tools_3.4.3      purrr_0.2.4      yaml_2.1.14     
[19] compiler_3.4.3   memoise_1.1.0    knitr_1.17       tibble_1.3.4    
```

**Comment by lorenzwalthert** [comment]
Thanks @joranE for reporting this. Here is what I think happened in your case:
You use crayon version 1.3.2. The current version of `crayon` (1.3.4) exports the function `col_align`. The package `cli`, which `styler` depends on, imports `crayon::col_align` ((https://github.com/r-lib/cli/blob/master/R/boxes.R#L39 and https://github.com/r-lib/cli/blob/master/DESCRIPTION) without specifying a minimal version for `crayon`. I think the minimal version of the depenedency of `cli` on `crayon ` should be 1.3.4, since the function `col_align` has not been an exported function until crayon 1.3.4 (which I found out by looking at the NAMESPACE file of the previous versions of crayon on CRAN),

Quick Fix: Install an updated version of crayon from CRAN and style again. It should work.

In addition, we should suggest the maintainers of `cli` to specify `crayon >= 1.3.4` in their DESCRIPTION with making reference to this issue. Do you want to do that via an issue / PR in `r-lib/cli` or should I do that?

**Comment by joranE** [comment]
Thanks for the quick explanation. Glad it turned out to be simple. Since you seem to have a handle on it, I'll leave the additional issue/PR for `cli` to you...

**Comment by lorenzwalthert** [comment]
Ok cool. So I assume your problem is solved then.

**Comment by lorenzwalthert** [comment]
Ok cool. So I assume your problem is solved then.
