### ISSUE TITLE
installation of styler does not fail when imports are not installed

### ISSUE THREAD

**Issue by RMHogervorst** [r-lib/styler#337]
Thanks for the great package! 

I'm in an offline environment and found that the styler package installs from zipfile (from CRAN) just fine.
However, I'm used to packages failing to install when the imports are not installed. 
Styler only complained later on when enc, and rematch2 were not installed.

You might want to change this?

**Comment by lorenzwalthert** [comment]
Thanks @RMHogervorst for reaching out. Are you sure this is a styler rather issue rather than something related to your particular environment? We had no complaints about installation problems so far. The only problem that can come up with the current CRAN version is that styler won't work in some cases if you don't have dplyr installed (#324).

**Comment by RMHogervorst** [comment]
Let me check on another computer, good point !

**Comment by RMHogervorst** [comment]
weird. on a linux machine, the installation failed as expected. 

I guess it does have something to do with the machine / environment. I'll close the issue for now
