### ISSUE TITLE
Other style guides

### ISSUE THREAD

**Issue by krlmlr** [r-lib/styler#340]
What would it take to support the following styles?

- @yihui's, e.g. in [tinytex](https://github.com/yihui/tinytex)
    - e.g., use `=` for assignment, use `'` for strings
- @wlandau's in [drake](https://github.com/ropensci/drake)
    - start argument list on the following line in a function declaration, no space between `)` and `{`

I'm sure there's a related postponed issue, but I haven't looked.

**Comment by lorenzwalthert** [comment]
I think there is no postponed issue with concrete plans on other style guides. However, I created a style guide that removes all comments in https://github.com/r-lib/styler/issues/334#issuecomment-361623797, and that was quick. So I think it's not a lot of work. For me, the question is also how we want to handle style guides other than the tidyverse style guide in general:

* Should *third-party* style guides (contributed by anyone) be implemented in styler or distributed via an another package we maintain (e.g. named `styleguides`) that collects style guides or should people write their own packages when they implement style guides? We could even put the tidyverse style gude into `style_guides` and make `styler` a pure infrastructure package.
* How can we ensure that contributed style guides are of high quality? Do we require third-party style guides to pass certain unit tests? Should the testing framework be used that was developed to unit test the tidyverse style guide?

I think these questions are important to make explicit decisions on as the number of third-party style guides may grow over time and a consistent strategy should be adopted. What's your @krlmlr take on that?

**Comment by krlmlr** [comment]
For these two I'd be fine if they lived in *styler* but were not exported for now. It feels like we need to play with a "proof of concept" first before thinking about organization. I'd let the handling of additional style guides be part of the upcoming GSoC project.

**Comment by lorenzwalthert** [comment]
I am currently working on implementing a style guide for the mlr package within styler: https://github.com/mlr-org/mlr/issues/2278

**Comment by riccardoporreca** [comment]
On the topic of _supporting_ custom style guides, you might also want to consider the possibility of 
selecting the style guide used by the RStudio addins.
I have actually an implementation of this as an additional "Set style" addin in fork [miraisolutions/styler](https://github.com/miraisolutions/styler), which I have been using already to play with some style guide customization.
I did not open a dedicated issue / PR, but would be happy to do so.

**Comment by lorenzwalthert** [comment]
Thanks @riccardoporreca. I'll fork your fork (haha) and try it out when I get the chance. I first want to submit styler 1.02. to CRAN

**Comment by riccardoporreca** [comment]
Sure, go ahead with the `styler %>% fork %>% fork` when you get a chance.
Happy 1.0.2 release.

**Comment by lorenzwalthert** [comment]
Working on the mlr style guide. Reference: https://github.com/mlr-org/mlr/issues/2278

**Comment by lorenzwalthert** [comment]
Related: a blog post for modifying the tidyverse style guide if your are not a style that expert: https://lorenzwalthert.netlify.com/posts/customizing-styler-the-quick-way/

**Comment by lorenzwalthert** [comment]
Related: a blog post for modifying the tidyverse style guide if you are not a styler expert. https://lorenzwalthert.netlify.com/posts/customizing-styler-the-quick-way/

**Comment by Robinlovelace** [comment]
Heads-up @krlmlr I've had a bash at implementing `yihui_style()` in this PR: #449.

Feedback welcome!

**Comment by lorenzofanchi** [comment]
I tried to use "Set style" from the add-in menu in RStudio, and set it to
`styler::tidyverse_style(scope = 'line_breaks'`

This break styling, throwing the following errors:

> > styler:::style_active_file()
> Using style `styler::tidyverse_style(scope='line_breaks')`
> Error in get_addins_style_fun()() : attempt to apply non-function
> > styler:::style_selection()
> Using style `styler::tidyverse_style(scope='line_breaks')`
> Error in style(...) : could not find function "style"

Am I doing something wrong, or can I not customize the styling in this way?

**Comment by lorenzwalthert** [comment]
Not currently, but we are just working on that for a week or so (#500). Please install that branch from GitHub and tell me if it works:

```r
remotes::install_github("r-lib/styler#500")
```

**Comment by lorenzofanchi** [comment]
Removed old package using `remove.packages` and installed new one as you suggested. Results in following error:

> > library(styler)
> > styler:::style_selection()
> Using style transformers`styler::tidyverse_style(scope = 'line_breaks')`
> Error in style(...) : could not find function "style"

**Comment by lorenzwalthert** [comment]
I am not sure I can reproduce this. Can you re-start R and RStudio?

**Comment by pat-s** [comment]
Trying to use [ale](https://github.com/w0rp/ale) with `styler` for VIM. There is an option to set the style guide. However, if I am not mistaken there is currently only the tidyverse style guide supported, right?

I know that you can set the style for the addin in `options()` but for the ALE plugin an exported style function from the `styler` package is required?

```
g:ale_r_styler_options                                 g:ale_r_styler_options                                                │ 32
                                                       b:ale_r_styler_options                                                │ 33
  Type: String                                                                                                               │ 34
  Default: 'styler::tidyverse_style'                                                                                         │ 35
                                                                                                                             │ 36
  This option can be configured to change the options for styler.                                                            │ 37
                                                                                                                             │ 38
  The value of this option will be used as the style argument for the                                                        │ 39
  styler::style_file options. Consult the styler documentation                                                               │ 40
  for more information.
```

I do not know how I should specify an external style function via this setting. 
Maybe a similar option named `styler.ale.style` could be implemented?

Some of our devs are working in VIM and it would be great to use the new styler ale implementation!

**Comment by lorenzofanchi** [comment]
I did the following:
1. remove package using `remove.packages('styler')
2. restart RStudio
3. install using `remotes::install_github("r-lib/styler#500")
4. restart RStudio
5. open file and tried to style, results as follows

Styling active document:
```
> styler:::style_active_file()
Using style transformers`styler::tidyverse_style()`
```
**works**

Style selection:
```
> styler:::style_selection()
Using style transformers`styler::tidyverse_style()`
Error in style(...) : could not find function "style"
```
does **not** work

**Comment by lorenzwalthert** [comment]
@lorenzofanchi sorry I missed that you were styling the selection only. Thanks for the hint. It should be fixed now in the aforementioned branch.

**Comment by lorenzofanchi** [comment]
@lorenzwalthert awesome, I'll try the updated version now!

Another question: is the set style remembered across RStudio restarts?

**Comment by lorenzwalthert** [comment]
No, it is not. You need to put something like this in your .Rprofile (e.g. via `usethis::edit_r_profile()`): 

```r
options(styler.addins_style_transformer = "styler::tidyverse_style(scope = 'line_breaks')")
```

So when R starts, it sets this option.

**Comment by lorenzofanchi** [comment]
Great stuff, thanks a lot for all the help and effort developing this incredibly useful tool!

**Comment by lorenzwalthert** [comment]
@pat-s: I don't use VIM, so I am not sure. Here is the PR in the ale repo: https://github.com/w0rp/ale/pull/2401/files.

From looking at the diff, I can at least tell that you'd need a function name there from some namespace. But you could use the mlr-style branch fork the fork you got from me and then specify that as the option, i.e. `styler::mlr_style`

If it is not working, maybe @tvatter could jump in. Also @tvatter, I think as we saw with #500, it is better to supply the transformers, not the style, because that would allow for much richer style specification. Should we do a breaking API change PR to fix this problem before the next release?

**Comment by tvatter** [comment]
Yeah, sorry, I didn't know much about `styler` and didn't really take the time to read the doc before implementing in ale. I can do a PR to ale to remove `ale_r_styler_options` and add `ale_r_styler_style` and `ale_r_styler_transformers` as two separate options if that provides more flexibility. In any case, using `styler::mlr_style` or any style defined in the namespace of `styler` or (in the namespace of any locally installed package) should work with the current version no?

**Comment by pat-s** [comment]
> From looking at the diff, I can at least tell that you'd need a function name there from some namespace. But you could use the mlr-style branch fork the fork you got from me and then specify that as the option, i.e. styler::mlr_style

I did that and it did not work. But I accidentally had CRAN styler installed for some reason. It works with the fork just as expected :+1: 

@tvatter 
If one specifies a non-valid style in `ale_r_styler_options` is is just silently ignored. Some kind of matching would be great here. But the prio for this is low I would say since there are only few VIM guys that use the new feature in general and even less that use a custom style.
Thanks for all your work on this!

**Comment by lorenzwalthert** [comment]
@pat-s ok great it worked. But the customization is not just for other style guides, also for customization *within* the tidyverse style guide. I.e. if one does want to style with scope `tokens` only, they could set the style transformers: 

```r
tidyverse_style(scope = "linebreaks")
```

To achieve that.

**Comment by pat-s** [comment]
What is the current policy dealing with custom style guides? Updating my fork constantly with all `styler' commits is tedious. I see that there is also #451 and possibly others?

I see the problem related to dealing with custom style guides (ensuring quality, responding to updates/PR). Maybe the easiest would be to have _styler_  being the API with custom packages that serve specific style guides. 
These would then simply "depend" on `styler` and only consist of e.g. `mlr-style.R`. 
Of course loading these guides via the RStudio extension (or `ale` for VIM) might get a bit more complicated then.

**Comment by Robinlovelace** [comment]
Heads-up @pat-s I had a go at something similar to mlr styles here: https://github.com/r-lib/styler/pull/451

Would happily join forces on something similar - not sure what the difference between 'mlr style' and 'equal style' is though...

**Comment by pat-s** [comment]
> Would happily join forces on something similar - not sure what the difference between 'mlr style' and 'equal style' is though...

Have no clue about your style. Major diffs of the "mlr-style" are to use 2 spaces for indentation and `=` instead of `<-`.

**Comment by Robinlovelace** [comment]
Thanks for the clarification @pat-s. I'm not too fussed about 2 spaces (as opposed to tab?) indentation and, as you would expect, 'equals style' (`Yihui style was another proposed name) also uses `=` assignment. If you point me towards the version of the style your using and I'll take a look.

**Comment by pat-s** [comment]
[Here](https://github.com/pat-s/styler/tree/mlr-style) is the repo for the mlr-style.

**Comment by loganknecht** [comment]
Hello!

I am a programmer working in an existing R codebase that is not consistent and I'm looking for some easy wins to get it to a consistent styling.

This appears to be a wonderful package, but it is very unclear how to support custom stylings that can be shared across the team environment.

I have just integrated a `.linter` file in our project directory and that was wonderful
https://github.com/jimhester/lintr

However I see no equivalent for how to do so in `styler`

Do you have guidance on how to support custom configurations AND configure it such that other teams working in this repository will default to those settings?

**Comment by lorenzwalthert** [comment]
First, in case you have not seen these, I point to a few existing resources related to your question of creating a new style guide: 

- remove rules form the tidyverse style guide: https://lorenzwalthert.netlify.com/post/customizing-styler-the-quick-way/
- create your own style guide from scratch: https://styler.r-lib.org/articles/customizing_styler.html
- the mlr style guide. This is a clone of r-lib/styler that is kept up to date with upstream and exports another style guide too: https://github.com/pat-s/styler/tree/mlr-style
- the one-liner package (removes all line breaks spaces if possible). This is implemented as a standalone R package that imports core functionality from styler with `:::`, which won't pass `R CMD check`. https://github.com/lorenzwalthert/oneliner/blob/master/R/rules.R

If you read this thread carefully, it becomes evident that there is no final solution to this problem. Maybe not yet. The cleanest would probably be to create a `styler.infra` package so people can create standalone R packages like one-liner, but that would be a lot of work on our side.

In any case, we don't really recommend creating your own style guide unless you have very good reasons for it. Since the tidyverse style guide is very popular and in our perspective elegant, we recommend to use it in almost all projects. Also note that it is *non-invasive* and you have a few options to customise it in many ways. Check `?tidyverse_style` for details. Since `v.1.3.0`, we also support ignoring some lines for styling, since `v1.2.0`, alignment detection is supported for function calls.

Sharing of custom style guides is also a bit difficult. 

- You can customised the Addin as discussed in `?styler_addins`, but this won't affect functions like `style_pkg()`. So for those, you'd need to supply your style guide every time you call the function.
- You can enforce styling upon committing with https://github.com/lorenzwalthert/precommit, which I believe is the preferred way of using styler - and there you can specify which style from which package to use.
- We have a discussion to store the arguments to `style_file()` and friends in a config, see #319.

**Comment by Robinlovelace** [comment]
Heads-up anyone following this and @yihui, and @pat-s in particular I've created a minimal {styler.equals} package building on a nice template by @lorenzwalthert: https://github.com/Robinlovelace/styler.equals

There's also this: https://github.com/ropensci-review-tools/spaceout

Not sure if these can go on CRAN due to use of `styler:::` calls, any ideas on that welcome and, more broadly, any ideas for what the style guide should contain? Many thanks!

**Comment by MichaelChirico** [comment]
> Not sure if these can go on CRAN due to use of styler::: calls

most natural seems to be requesting export of key helper functions :)

**Comment by Robinlovelace** [comment]
Was wondering if that would be a possibility and have opened an issue: https://github.com/r-lib/styler/issues/974. Thanks for the suggestion Michael!
