### ISSUE TITLE
Styler does not respect knitr chunk options in R scripts

### ISSUE THREAD

**Issue by samhinshaw** [r-lib/styler#361]
Styler formats chunk options in R scripts [formatted for `spin`ning to markdown](https://yihui.name/knitr/demo/stitch/#spin-comment-out-texts) from: 
```
#+
```
to
```
# +
```

For an example, run styler on the [knitr spin example](https://github.com/yihui/knitr/blob/master/inst/examples/knitr-spin.R). As a result, chunk names are turned into regular code comments.

**Comment by lorenzwalthert** [comment]
Hi @samhinshaw, thanks for pointing out. I heard of spinning but I did not know the details. So do you suggest to always keep `#+`, just as we keep `#'`? I wonder whether there are use cases where someone wanted a space but forgot it. Because we would no longer be able to detect that if a plus follows. Maybe we can match the whole line with regex? And is it always preceded with at least two line breaks? 

Also, probably need to adapt documentation since we include quite a few special cases now (see #305, #345 etc.)

**Comment by samhinshaw** [comment]
I think it would make sense to preserve `#+`. I cannot think of too many cases in which this would prevent formatting. 

Because of spin's flexibility, the chunk option does not need to be preceded or proceeded by anything in particular&mdash;it could be code, line breaks, roxygen comments, or 'regular' comments.
```
#' Now let's do X in this next example:
#+ example2
ggplot(...)
```

The nice thing about spin is that you do not need any special formatting within an `.R` script to use it! Unfortunately, this also limits detection options. However, you can add a YAML header a la R Markdown if you wish:

```r
#' ---
#' title: 'Example Document'
#' author: 'Sam Hinshaw'
#' output: github_document
#' ---
```

So I suppose another way to do this would be opt-in to by only preserving `#+` when a roxygen-commented YAML chunk exists.

**Comment by lorenzwalthert** [comment]
Ok. I think we need simple rules. So I think let's preserve #+ everywhere.

**Comment by lorenzwalthert** [comment]
You can use the patch until this is merged into master / a new release appears on CRAN:
```r
remotes::install_github("r-lib/styler#362")
```
