### ISSUE TITLE
Support for .Rnw files

### ISSUE THREAD

**Issue by Hasnep** [r-lib/styler#431]
Sorry if this is a dumb thing to ask, but are there any plans to add support for .Rnw files?

If not, how difficult would it be for me to add this as someone who is unfamiliar with developing R libraries?

**Comment by lorenzwalthert** [comment]
> Sorry if this is a dumb thing to ask, but are there any plans to add support for .Rnw files?

It's not 😄. I indeed thought about it some time ago, but since I am not using `.Rnw` myself, I decided not to look into it. To be honest I am not sure how easy that is for you. @jonmcalder and I implemented that feature in #233. I think it should not be too hard to adapt the package to handle `.Rnw` too since from what I can tell, it looks as if we mainly have to change the regex that is dedicated to match `{r ` now. But if you are not familiar with R package development workflows, even a small change in the  source code can be tricky. @jonmcalder would you be interested in extending styler in that direction?

**Comment by jonmcalder** [comment]
Sure - this seems feasible and I'd be happy to assist with this. @Hasnep if you'd like to work on this together let me know and we can chat further?

**Comment by lorenzwalthert** [comment]
Cool Jon. Thanks for taking care of this. Looking forward to review a PR 😊

**Comment by Hasnep** [comment]
Thank you both for your quick responses. I don't think my R skills are at the level where I can usefully contribute yet.

**Comment by lorenzwalthert** [comment]
@Hasnep interested in testing this feature? Advised: save + commit / backup a copy of the files you apply styler first.

```r
remotes::install_github("r-lib/styler#434")
```

Then you can proceed as usual after restarting R (Cmd + Shift + F10 in RStudio).

**Comment by lorenzwalthert** [comment]
Closed with #434.
