### ISSUE TITLE
Snake case

### ISSUE THREAD

**Issue by tvatter** [r-lib/styler#488]
Hi,

I wondered about the possibility to convert variable and/or function names to snake_case.

Something like that could be based on the [snakecase](https://cran.r-project.org/web/packages/snakecase/index.html) package?

**Comment by lorenzwalthert** [comment]
Thanks for the suggestion. Actually, I think this is beyond the scope for styler. Because we could not guarantee code is valid after styling, which is currently possible when `scope < "tokens"`. Also, it migh prove very hard to do the right thing  in all situations. Just take this code: 

```r
NotSnake <- 3
not_snake <- 2
not_snake + NotSnake
```

How should styler change this code? Also, what about 

```r
t_score <- TScore(x)
```

In short, I think such a conversion would be handy but too much can go wrong. In addition, naming is an important part of programming, so I am not sure if this should be automated to the degree you propose.

**Comment by tvatter** [comment]
Right, it totally makes sense, thanks for your answer.
