### ISSUE TITLE
Don't re-check style on unchanged code

### ISSUE THREAD

**Issue by jackwasey** [r-lib/styler#491]
Currently, it seems that every file, is checked regardless of whether it is updated. Would it be reasonable to check file timestamps and cache them either in the package or in a tidy place in the user's home directory, or even `$TMP`? Or use `digest` to cache the hashes instead of timestamps? This would save a lot of time for bigger R packages, and make this easier to run styler frequently, or possibly automatically with each git commit (if only to check whether styling is due). Q.v. https://github.com/r-lib/styler/issues/467

**Comment by lorenzwalthert** [comment]
I think this is a duplicate of #320, which obviously is hard to find. Do you mean the environment variable `$TMP`? I think that's not a good idea because it is not persistent. In #320, we had `digest` in mind as well. However, I am not sure what the best place to store this information is. Let's continue in #320.
