### ISSUE TITLE
force styler to add quote for library function

### ISSUE THREAD

**Issue by yech1990** [r-lib/styler#495]
`library(ggplot2)` --> `library("ggplot2")`

**Comment by lorenzwalthert** [comment]
Thanks @yech1990, I opened tidyverse/style#132 because the general principle of this repo is to only implement rules that are specified there. Note that we can only conduct the above conversion with certainty (provided the tidyverse style guide favors `library("ggplot2")` in case there is no `character.only = TRUE` in the `library()` call. Because otherwise, you could

``` r
ggplot2 <- "styler"
library(ggplot2, character.only = TRUE)

search()
#>  [1] ".GlobalEnv"        "package:styler"    "package:stats"    
#>  [4] "package:graphics"  "package:grDevices" "package:utils"    
#>  [7] "package:datasets"  "package:methods"   "Autoloads"        
#> [10] "package:base"
```

<sup>Created on 2019-04-21 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by lorenzwalthert** [comment]
We have decided in https://github.com/tidyverse/style/issues/132 to not add a rule in the tidyverse style guide but I implemented it anyways in the experimental branch in  https://github.com/lorenzwalthert/styler/tree/library. Note that as of now, we don't think we will merge this into `r-lib/styler@master` anytime and that this branch is experimental and won't be kept up-to-date with `r-lib/styler@master`.
