### ISSUE TITLE
Assignment operator replacement within function calls drops side effects

### ISSUE THREAD

**Issue by pat-s** [r-lib/styler#513]
In the following example, `styler` corectly changed `<-` to `=` based on our style guide (mlr).

However, in this case, `<-` is not replaceable since using `=` would not be valid R6 notation here.

https://github.com/mlr-org/paradox/commit/095ab870916f0497a4d8dfb60e6c57e04363b2cf#diff-70733be47fa2d7f0bf47754e8a00afa4L69

This looks like an edge case that is maybe hard to tackle. I can't really add more context to this at the moment. 

cc @mllg

**Comment by lorenzwalthert** [comment]
I am not sure I can follow. I don't think the problem is related to R6, but rather that `<-` has a different meaning than `=` when used within function calls: 

``` r
c(a <- 3)
#> [1] 3
c(b = 2)
#> b 
#> 2
a
#> [1] 3
b
#> Error in eval(expr, envir, enclos): object 'b' not found
```

<sup>Created on 2019-05-12 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

And this is not respected with the mlr stlye guide: 

``` r
text <- "c(a <- 3)
c(b = 2)
a
b"

styler::style_text(text, style = styler::mlr_style)
#> c(a = 3)
#> c(b = 2)
#> a
#> b
```

<sup>Created on 2019-05-12 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by pat-s** [comment]
Ahh I see. Thanks for the heads-up. I've never come across this general issue so far.

How can we get rid of it? I guess it is hard to automatically guess the intention within a function call whether `<-` is correct or should be replaced? Even when checking the args of a function whether the provided expression fits does not really solve the case as it could be passed to a possible ellipsis arg. 

Maybe the only use case to use `<-` within function calls are the `expect_*()` functions in _testthat_? So turning the fixer off for these kind of functions could be a possible workaround. But maybe you have a better idea here?

**Comment by lorenzwalthert** [comment]
I think we can simply check if the `<-` was used within a function call and then assume this was intentional. I made it work already locally. Will push it to my fork so you can rebase. That would be a good time to rebase the mlr branch anwyays (I had some merge conflict I resolved). Then I can make a PR to your fork.

**Comment by lorenzwalthert** [comment]
Done, see pat-s/styler#1.
