### ISSUE TITLE
Conditional line breaking of closing braces

### ISSUE THREAD

**Issue by pat-s** [r-lib/styler#514]
Is the following case supported?

- If braces open on the same line, they should close on the same line (see EX 1) -> needs adjustment
- If braces do not open on the same line, they should also close on different lines (See EX 2) - works as expected

``` r
ex1 = "map_dtr(x, function() {
  function1()
})
"

styler::style_text(ex1, style = styler::mlr_style)
#> map_dtr(x, function() {
#>   function1()
#> }
#> )


ex2 = "public = list(

  obj = function() {
    function1()
  }
)
"

styler::style_text(ex2, style = styler::mlr_style)
#> public = list(
#> 
#>   obj = function() {
#>     function1()
#>   }
#> )
```

<sup>Created on 2019-05-13 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by lorenzwalthert** [comment]
I believe this feature was deliberately turned off for mlr style according to this rule: 


> 1. **Curly braces:**
>   The opening curly brace goes on the same line as the respective syntactic element it belongs to and never on its own line. Always have one space before the opening brace `{`. The closing curly brace `}` goes on its own line, except if it occurs before an `else` statement, see the following point on `if` statements.

From the [here]. Is this still the style guide used within mlr? I think it was turned off deliberately because it exists for the tidyverse style, or at least if formatted that way, this element is not changed: 

``` r
ex1 <- "map_dtr(x, function() {
  function1()
})
"

styler::style_text(ex1)
#> map_dtr(x, function() {
#>   function1()
#> })
```

<sup>Created on 2019-05-18 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>


By the way: The Addins API has changed, you should supply a style *transformer* now, not a style guide, i.e. `mlr_style()` instead of `mlr_style()`. That should be updated here: https://www.notion.so/Style-Guide-740bc663207a4bbb9a457987bda6fd91.

**Comment by pat-s** [comment]
You are right, we deliberately removed it. I reverted this change now again.
As our style guide is a mix of different opinions, not all decisions are crystal clear and accepted by everyone.

Also this style implementation goes on for a while now and I do not have all the changes always in mind. Thanks for being lenient with us.

The rule I turned off btw was "add_line_break_before_round_closing_after_curly".

> By the way: The Addins API has changed, you should supply a style transformer now, not a style guide, i.e. mlr_style() instead of mlr_style(). That should be updated here: notion.so/Style-Guide-740bc663207a4bbb9a457987bda6fd91.

Thanks, done.
