### ISSUE TITLE
style_selection() should preserve trailing newline

### ISSUE THREAD

**Issue by hadley** [r-lib/styler#519]
Given

````
```{r}
1+2
```
````

If I select `1+2` and then style the current selection, I get

````
```{r}
1+2```
````

**Comment by lorenzwalthert** [comment]
Thanks. I think the problem described only occurs when the whole line is selected with the Addin (see #520). However, I think that we should also get this case right since I imagine it's common to select code like this if one uses the Addin, so we should resolve this in #520.

Side note: For styling a whole `.Rmd` document, there is support via both `styler::stlyle_file(...)` and `style_pkg(..., filetype = ".Rmd")` as well as through the `style active file`  Addin (I guess you knew this already, just for the record).
