### ISSUE TITLE
styler fails to correctly style syntactic rlang sugar {{

### ISSUE THREAD

**Issue by ellessenne** [r-lib/styler#526]
Hi!
I noticed that the new `{{ }}` operator from `rlang` is not styled properly; for instance, if I style the following lines

```r
library(rlang)
name <- "Jane"
list2({{name}} := 1 + 2)
```

I get the following:

```r
library(rlang)
name <- "Jane"
list2({
  {
    name
  }
} := 1 + 2)
```

Not sure what would be a good way of handling this specific operator (maybe @lionel- has an idea), I just thought about reporting it.

Anyway, thanks for `styler`: absolutely love the package!

Alessandro

**Comment by lionel-** [comment]
We're currently leaning towards `foo({{ var }})`.

**Comment by lorenzwalthert** [comment]
Thanks guys. Is there a rule in the tidyverse style guide planned? I think we can implement the suggested style from @lionel- without much work. Is `{{` space or line break *in*-sensitive, i.e. does it have the same meaning as `{ {` or `{\n{` or does styler currently change the meaning in the example demonstrated by @ellessenne?

**Comment by ellessenne** [comment]
The two examples return the same result:

``` r
library(rlang)
name <- "Jane"

list2({{name}} := 1 + 2)
#> $Jane
#> [1] 3

list2({
  {
    name
  }
} := 1 + 2)
#> $Jane
#> [1] 3
```

<sup>Created on 2019-06-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

...I just think the latter is ugly! :smiley: Jokes aside, I think the `{{ }}` operator should not be broken into multiple lines - otherwise it becomes counter-intuitive?

**Comment by lorenzwalthert** [comment]
I agree that styler's current behavior is not ideal, but I simply asked because if the result would change, the issue would have been much more urgent to fix. We are definitively going to so something about it. I think the consensus is: 

* leave `{{` as is.
* change `{ {` into `{{`.

not sure about `{\n{` and similar, but probably it should also be turned into `{{` with `strict = TRUE` in `styler::tidyverse_style()`.
