### ISSUE TITLE
Redundant line breaks in function header not removed when formatting

### ISSUE THREAD

**Issue by michaelquinn32** [r-lib/styler#549]
After resolving #541, `tryCatch` blocks now terminate in a new line.

```
code <- "tryCatch({
  my_options <- options()
  print('hello!')
},
error = function(e) e)
"
styler::style_text(code)
#> tryCatch(
#>   {
#>    my_options <- options()
#>    print("hello!")
#>  },
#>  error = function(e) e
#> )
```

This seems like one good case from #125, but there are examples in that issue where the original formatting was considered correct.

Similarly, function signatures that used a wrapped style for arguments also end in an empty new line.

```
code <- "function(
    my_indendented_arg, and_another) {
  print('hello')
}"
styler::style_text(code)
#> function(
#>          my_indendented_arg, and_another) {
#>   print("hello")
#> }
```

These seem to be related as cases where there are empty new lines after an opening paren.

Thanks!

**Comment by lorenzwalthert** [comment]
I think I can't follow. 

First, I believe indeed that some formatting previously considered correct (also from #125) is now considered not correct anymore, for example 
```r
tryCatch({
  my_options <- options()
  print("hello!")
},
error = function(e) e
)
```

Is no longer desired and is now turned into: 

```r
tryCatch(
  {
    my_options <- options()
    print("hello!")
  },
  error = function(e) e
)
```

This is intentional and not related to #541, it was introduced in #543.

I believe the second issue you raise could be re-formulated with *redundant line breaks in function formals / signatures / headers are not removed*. I.e. 
```r
function(
         my_indendented_arg, and_another) {
  print("hello")
}
```
Will be returned unchanged by styler. This is indeed not nice, but not new, it's been the same in styler 1.1.1 (current CRAN release).

If my understanding is correct, then I'd suggest renaming the issue accordingly.

**Comment by michaelquinn32** [comment]
Thanks for the feedback!

If the first case is intentional, then they aren't related. I'll rename the issue to focus on redundant line breaks.

**Comment by lorenzwalthert** [comment]
So for 
```r
code <- "function(
    my_indendented_arg, and_another) {
  print('hello')
}"
```

Do you think the preferred output is 
```r
code <- "function(my_indendented_arg, 
                  and_another) {
  print('hello')
}"
```
or 
```r
code <- "function(my_indendented_arg, and_another) {
  print('hello')
}"
```

**Comment by michaelquinn32** [comment]
Ideally, the preference between the two would depend on the character length of option 2. Fixing long lines has been some work, and I know that this is an issue that you're addressing.

This means that the first option is fine for this case. In all likelihood, the indented signature was probably used to address a line that was too long.

**Comment by michaelquinn32** [comment]
@jimhester The `tryCatch` behavior described above is now throwing lintr errors:

```
tryCatch(
  {
    my_options <- options()
    print("hello!")
  },
  error = function(e) e
)
```

Since it places an open curly brace on its own line. Should I open a PR for lintr?

**Comment by jimhester** [comment]
```r
tryCatch(
  {
    my_options <- options()
    print("hello!")
  },
  error = function(e) e
)
```

Is quite ugly, I have no intention of changing how lintr behaves with regards to this, if you want this you can edit your default linters to accept this style.

**Comment by lorenzwalthert** [comment]
Ok, interesting. @jimhester how would you format this? After debating with @krlmlr, he finally convinced me in #428 that this is preferred so I changed it in styler #543 -.-  

I think we should formalize a rule for braces in function calls in https://github.com/tidyverse/style and then make sure styler and lintr are on par. I'll open an issue.

**Comment by jimhester** [comment]
I always format them like this, I don't really agree with what is in the style guide.

```r
tryCatch({
    my_options <- options()
    print("hello!")
  },
  error = function(e) e
)
```

**Comment by lorenzwalthert** [comment]
Ok, one reason we did not opt for this is because styler's indention logic is implementing the logic that you can only indent one level every new line (I think, can't exactly remember).

**Comment by jimhester** [comment]
If you do want the arguments to match up I think doing so explicitly works better, and also won't have lints with lintr.

```r
tryCatch(
  expr = {
    x <- scan()
    cat("Total: ", sum(x), "\n", sep = "")
  },
  interrupt = function(e) {
    message("Aborted by user")
  }
)

**Comment by lorenzwalthert** [comment]
So how do you indent `test_that()` calls then?
```r
test_that("here", {
    "two-levels"
})
```

**Comment by krlmlr** [comment]
I fully stand behind the current implementation in styler. For me it's important that the code style applied automatically is nearly identical to what would happen when you type the same code manually, because this decreases the burden when editing the code.

For now it seems that users of both lintr and styler need

```r
tryCatch(
  expr = {
    ...
  }
)
```

. The following produces lints

```r
tryCatch(
  {
     ...
  }
)
```

while the latter won't be produced by styler currently:

```r
tryCatch({
    ...
  }
)
```

This looks like a situation where everybody can find their peace. Let's focus on `function(\n...)` here and discuss `tryCatch()` elsewhere.
