### ISSUE TITLE
Styler does not preserve new line characters

### ISSUE THREAD

**Issue by michaelquinn32** [r-lib/styler#551]
Long strings that have new line characters have literal new lines added after styling:

``` r
code <- "                                                              
function() {                                                           
paste('I am loooooooooooooooooooooooooong, and I have a new line: \n')
}                                                                      
"                                                                      
styler::style_text(code)                                               
#> function() {
#>   paste("I am loooooooooooooooooooooooooong, and I have a new line: 
#> ")
#> }
```

Ideally these characters would be preserved.

**Comment by lorenzwalthert** [comment]
# Context

This actually has been discussed in the past, there is even FIXMEs in the unit tests. Most relevant: #458 and #459.

Note that your problem should only occur with single quotes. This seems to be rooted in the way we convert single to double quotes. in https://github.com/r-lib/styler/issues/458, we made another edge case work but caused the one you bring up here to fail. Prior to https://github.com/r-lib/styler/issues/458, we had [this](https://github.com/r-lib/styler/pull/459/files#diff-78f2f17e8a3f50cf8a031424b2bfbb28L104-L108): 
```r
    vapply(
      lapply(pd_flat$text[str_const][str_const_change], parse_text),
      deparse,
      character(1L)
    )
```
which is basically `deparse(parse(text = ..., keep.source = TRUE)[[1]])`.

It was intended to do the follwing: 
- Remove any quotes, 
- then and add quotes

taking advantage of the fact that quotes added will always be double quotes, so this is implements the rule "convert single to double quotes". This should also take care of escaping (removing then adding) and the case when single and double quotes are mixed in a string (I believe it's non-trivial).

However, it won't work in the second case because the symmetry breaks. 

# Problem - narrowed down

We can see that the below code does not just replace quotes, but in the second example, also adds another `\`.

``` r
not_embedded <- "'a\\nx'"
p1 <- styler:::parse_text(not_embedded) # removes backslashes + quotes
p1
#> [1] "a\nx"
deparse(p1) # adds backslashes and quotes
#> [1] "\"a\\nx\""

embedded <- "'a
x'"
embedded
#> [1] "'a\nx'"
p2 <- styler:::parse_text(embedded) # does not remove backslashes, removes quotes
p2
#> [1] "a\nx"
deparse(p2) # adds backslashes and quotes
#> [1] "\"a\\nx\""
```

<sup>Created on 2019-10-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Because the desired result of `deparse(p2)` is ` "\"a\nx\""`. We can arrive at the expected result for case two with the current solution propsed in [#459](https://github.com/r-lib/styler/pull/459/files#diff-78f2f17e8a3f50cf8a031424b2bfbb28R115-R116), which basically is: 
``` r
parse_text(embedded) %>%
     paste0("\"", ., "\"")
```

However, then, we'd not get the first case right if we appli that to all code.

# How to resolve this

I am not sure I am enough of a computer scientist here to solve that adequately. @krlmlr you came up with this whole `deparse(parse())` idea, maybe you can fix your own bug?  👀 😄. My thoughts: Solve this with case distinction (referring to the version when it is already read into R and escaped once):

- \n and friends has a raw representation like 0a.
- \\n is understood as two character (\\ and n), i.e. 5c and 6e.
- check if the string contains the first case or the second case or both.
- If both, don't do anything and leave the single quotes.
- if just one, resort to the strategy that currently works.

**Comment by lorenzwalthert** [comment]
If you can, please improve on that solution. I already opened #553 and added unit tests, so you can easily verify your solution.
