### ISSUE TITLE
default_style_guide_attributes example fails to run

### ISSUE THREAD

**Issue by QuLogic** [r-lib/styler#613]
When building styler and running tests (with `R CMD check styler`), the above example fails. On 1.3.0,
```
Running examples in ‘styler-Ex.R’ failed
The error most likely occurred in:
> ### Name: default_style_guide_attributes
> ### Title: Initialize default style guide attributes
> ### Aliases: default_style_guide_attributes
> ### Keywords: internal
> 
> ### ** Examples
> 
> string_to_format <- "call( 3)"
> pd <- styler:::compute_parse_data_nested(string_to_format)
Error in cache_make_key(text, transformers) : 
  argument "transformers" is missing, with no default
Calls: <Anonymous> ... %>% -> eval -> eval -> <Anonymous> -> cache_make_key
Execution halted
```
and on 1.3.2,
```
Running examples in ‘styler-Ex.R’ failed
The error most likely occurred in:
> ### Name: default_style_guide_attributes
> ### Title: Initialize default style guide attributes
> ### Aliases: default_style_guide_attributes
> ### Keywords: internal
> 
> ### ** Examples
> 
> string_to_format <- "call( 3)"
> pd <- styler:::compute_parse_data_nested(string_to_format)
Error in text_to_flat_pd(text, transformers) : 
  argument "transformers" is missing, with no default
Calls: <Anonymous> ... %>% -> eval -> eval -> <Anonymous> -> cache_make_key
Execution halted
```
(Note, I do not yet have `data.tree` installed if that matters, as it still has some unpackaged dependencies.)

**Comment by lorenzwalthert** [comment]
Interesting. The reason is probably the cache. Seems like it is deactivated on CRAN while running the examples. 

``` r
cache_deactivate()
#> Error in cache_deactivate(): could not find function "cache_deactivate"
string_to_format <- "call( 3)"
pd <- styler:::compute_parse_data_nested(string_to_format)
#> Error in text_to_flat_pd(text, transformers): argument "transformers" is missing, with no default
```

<sup>Created on 2020-02-26 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

We should probably adapt the example and make it run independently of the cache state:

``` r
string_to_format <- "call( 3)"
pd <- styler:::compute_parse_data_nested(string_to_format, transformers = styler::tidyverse_style())
```

<sup>Created on 2020-02-26 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

What R version do you use?

**Comment by QuLogic** [comment]
R is 3.6.2; build command is just `LANG=C.UTF-8 _R_CHECK_FORCE_SUGGESTS_=0 /usr/bin/R CMD check styler` (note we start from an unpacked tarball from CRAN). See [scratch build here](https://koji.fedoraproject.org/koji/taskinfo?taskID=41924055) for exact list of packages.

**Comment by lorenzwalthert** [comment]
I am not sure I can provide technical assistance in the sense of why it does not fail on CRAN but your checks fail. 

I also took the CRAN tarball and checked the package and I could not reproduce the problem. Independently of this, I think we should make all examples work independently of the cache state, and I believe that would also resolve your problem. That I can do. But since we just had 3 very recent CRAN submissions, I think we are not going to release another version within the next month. What would be the implications for you if we'd not fix the problem soonish? 

I looked quickly into your work (packaging for Fedora) but I could not really understand what it is used for, so just out of curiosity: Why do Fedora users not just download from CRAN? Are you providing binaries for Fedora?

**Comment by QuLogic** [comment]
That is fine if there's no release. I assume that passing tests are a pretty good indicator that things are mostly working as normal, and I could just skip the examples temporarily. But since you've fixed it though, I guess I could also backport the fix as it has no real effect on users' code.

For pure-R packages, there's not as much benefit, but for ones with compiled code, it is (at least for my ancient laptop) much faster to pull down pre-compiled Fedora packages. Plus updates are handled in one standard place, and can be automated (if you turn it on.)

**Comment by lorenzwalthert** [comment]
Ok. Can you check if my fixes in #614 solve all your problems, i.e. make a tarball from the GitHub version and send it through your build pipeline?

**Comment by QuLogic** [comment]
In fact, I've already run 1.3.2 + the backported patch and it passes fine: https://koji.fedoraproject.org/koji/buildinfo?buildID=1474160

**Comment by lorenzwalthert** [comment]
Ok perfect.
