### ISSUE TITLE
Dry-run mode

### ISSUE THREAD

**Issue by select-id-from-users** [r-lib/styler#633]
Is it possible to run `styler` in dry-run/check-only mode, where it simply reports what would be formatted?

Our use-case for this is to use `styler` in a pre-commit hook on the developer's side, and as part of CI/CD tests once code has been received by git server.

Technically we could solve this by using temporary directories and a lot of copying and diff-ing. However it would be much simpler if `style_dir` accepted parameter `check_only=T` or `dry_run=T`.

We would then use the output of this function inside `stopifnot` for example, such that our scripts will fail, thereby halting the commit or failing the test run.

Python's code formatter `black` has this functionality: by running `black --check`, nothing gets modified and it will exit with non-zero exit code if something would have been formatted. This makes it very easy to use in pre-commit hooks and CI/CD tests.

**Comment by lorenzwalthert** [comment]
Currently, styler does not support a dry run. I am open to change this. We could change the API to include an argument `dry`, that is one of 

- `off` (default): Current behavior. Write back to file as side effect. Return tibble with summary invisible (as now).
- `on`: Never modify files, also return tibble summary **as if** thins were written back.
- `fail`: Fail if any file was modified. Never modify anything.

Any feedback on the design welcome. I think using boolean values would not allow us to differentiate these three cases. 

Thanks for providing context. For your use case, I don't really understand why you need this feature. I see the following alternatives:

- I wrote [`{precommit}`](https://github.com/lorenzwalthert/precommit) which includes a styler hook that fails if styling is not compliant because pre-commit hooks fail on non-zero exit status **and** on modification. So you could just use this? The hook fails if files are not style compliant. To run the hooks on all files, run `pre-commit` in the repo. This is how I think it's often done in a CI/CD setting.
- Assuming you have another framework to manage hooks (or none, i.e. simple scripts in `.git/hooks`), I am also not sure why this feature is needed. Because as per the documentation in `style_file` and friends, these function have the following return value: 

> Invisibly returns a data frame that indicates for each file considered for styling whether or not it was actually changed.

```r
result <- style_file("R/addins.R")
Styling  1  files:
 R/addins.R ✓ 
────────────────────────────────────────
Status	Count	Legend 
✓ 	1	File unchanged.
ℹ 	0	File changed.
x 	0	Styling threw an error.
────────────────────────────────────────
> result
# A tibble: 1 x 2
  file       changed
  <chr>      <lgl>  
1 R/addins.R FALSE  
```

So you could `stopifnot(any(result$changed))` and halt the CI/CD run. Also note on an unrelated note that for GitHub, there is the `\style` action as described in the README of this package to style code with styler.

Hope you can follow...

**Comment by select-id-from-users** [comment]
@lorenzwalthert Thanks for you reply.

I did see pre-commit (did not know you wrote it). In my workflow a pre-commit hook should not have any side effects. I saw the pre-commit code and as far as I understood, it will make the hook fail but also leave the files in a modified state. 

About half of the time when I do commits, I do it with `git add -p <file>` and then pick modifications I want to include. Maybe this workflow is not ideal, but I am used to it. So if the pre-commit hook would fail, the files would have my uncommitted modifications and then the `styler` modifications. Undoing only `styler` ones would be difficult.

My git skills are subpar and maybe this is a non-issue I described above. In any case, the pre-commit hook is not top priority for me and I could probably find a with the two alternatives you posted.

The CI/CD is example you described indeed makes sense. There it does not matter that files are modified because it's the end of CI/CD anyway. I think I will do it this way.

**Comment by lorenzwalthert** [comment]
Side note: 

> I did see pre-commit (did not know you wrote it). In my workflow a pre-commit hook should not have any side effects.

Not everyone likes it, but I think it's better that way because, as described in the [vignette](https://lorenzwalthert.github.io/precommit/articles/available-hooks.html)

> Other hooks like the styler hook write to files, and if that changes the file, the hook will fail, but this means you won’t need to modify the file manually, just stage the changes and try to commit again.

If you don't like the changes, you can discard them. But this would require to surpass the hook at the next commit attempt. This takes advantage of git's feature that staging is not the same as committing. Because you can inspect the diff styler made. You can see that in RStudio.

> My git skills are subpar and maybe this is a non-issue I described above

No we will implement it 😄 . Tonight 😄 .
