### ISSUE TITLE
braces in `glue` calls are styled to go on separate lines

### ISSUE THREAD

**Issue by IndrajeetPatil** [r-lib/styler#639]
I am not sure what the `tidyverse` style guide says here, but I would have expected the `glue` braces to remain on the same line (the same way the braces in `{{` operator from `rlang` is not styled to be on different lines).

- Observed

``` r
styler::style_text(
  "x <- 'cat'
glue::glue({ x })"
)
#> x <- "cat"
#> glue::glue({
#>   x
#> })
```

- Expected

``` r
styler::style_text(
  "x <- 'cat'
glue::glue({ x })"
)
#> x <- "cat"
#> glue::glue({ x })
```

**Comment by lorenzwalthert** [comment]
Thanks @IndrajeetPatil. I am not sure why you call them glue braces. I don't think they are related to glue, these are just normal curly braces, no? I also don't see why anyone would want to write this code that way, because
```r
x <- 'cat'
glue::glue({ x })
cat
glue::glue('cat')
cat
glue::glue(x)
cat
glue::as_glue('cat')
cat
# or simply 
x
"cat" # if you don't need the class
```

I.e. the braces are redundant. Also, omitting the quotes does not work `glue::glue(here is my {x})` so I am not sure this needs special treatment.

**Comment by IndrajeetPatil** [comment]
Sounds reasonable. Thanks for the detailed reply and explanation.
