### ISSUE TITLE
Styling Rmd files that are learnr tutorials

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [r-lib/styler#657]
In learnr tutorials it's possible to have free-form text in hints, and these go in an R chunk. `style_active_file()` fails on these chunks with an `unexpected symbol`. These chunks always have the text string `-hint` in them. Perhaps styler could overlook such chunks in learnr documents?

A gist with a simple learnr tutorial where styling fails can be found [here](https://gist.github.com/mine-cetinkaya-rundel/93001f321c3f37bebbf1b3a971c3e71d). The error is as follows:

```r
Error: <text>:1:6: unexpected symbol
1: What about
         ^
```

**Comment by lorenzwalthert** [comment]
Thanks @mine-cetinkaya-rundel. I have never worked with {learnr}, so I am not sure I get everything you are saying right. I observe: 

* If any R code chunk contains code that can't be styled, the whole document is not styled. This the case for all documents, not just {learnr} documents. Sometimes code chunks contain invalid R code on purpose and will be rendered correctly because they have `eval = FALSE`. That's at least a related discussion.
* If I understand the [docs](https://rstudio.github.io/learnr/exercises.html#Hints_and_Solutions) correctly, your case is an edge case because you want to use multiple hints and mix markdown with R code. There is already support for multiple R chunks and one markdown chunk. So instead of making styler work for the `-hint` exception, wouldn't it be more elegant to add support for mixed markdown / R code hints in {learnr} directly?

**Comment by mine-cetinkaya-rundel** [comment]
@lorenzwalthert You're right, that might be a more sensible approach. As you suggested, I was putting the text in the R chunk in order to have multiple hints. 

I'll close this and open an issue on the learnr repo. Thank you!

For others who might find themselves here, a workaround until there is a more elegant solution is to make the first hint in my example above a text string by quoting it, e.g. `"What about head()?"`. This way styler treats the contents of that chunk as a text string and is able to style the file.

**Comment by lorenzwalthert** [comment]
@mine-cetinkaya-rundel you can not add `tidy = FALSE` to rmd chunks, and the dev version of {styler} won't touch the chunk (code must not even be parsable), as discussed in #781.

**Comment by mine-cetinkaya-rundel** [comment]
Thanks, @lorenzwalthert! (I think you meant "you can **now** add? Just noting for someone else who might land on this issue in the future.)

**Comment by lorenzwalthert** [comment]
Now yes... Not *not*. :)
