### ISSUE TITLE
feature request: styling function definition with multiple arguments to one argument per line

### ISSUE THREAD

**Issue by IndrajeetPatil** [r-lib/styler#719]
The `tidyverse` style guide [mentions](https://style.tidyverse.org/functions.html):

![image](https://user-images.githubusercontent.com/11330453/106125865-f2017780-615c-11eb-84f2-322983d5d63d.png)

Although it doesn't explicitly recommend that when the function definition looks like the following, there should be one argument per line to improve readability, but I am guessing that this is something implicitly being hinted at? Not sure.

```r
styler::style_text(
'
foo <- function(posteriors, centrality = "median", dispersion = FALSE, ci = 0.89, ci_method = "hdi", test = c("p_direction", "rope"), rope_range = "default", rope_ci = 0.89, component = c("all", "conditional", "location"), parameters = NULL, ...) {}
'
)
#> 
#> foo <- function(posteriors, centrality = "median", dispersion = FALSE, ci = 0.89, ci_method = "hdi", test = c("p_direction", "rope"), rope_range = "default", rope_ci = 0.89, component = c("all", "conditional", "location"), parameters = NULL, ...) {}
```

Nevertheless, I was wondering if you think this (styling to one argument per line) is something that `styler` should be doing by default? Of course, it might not make sense to do this when there are only a few (3-4?) arguments present, but would have increasing utility the more arguments are present.

**Comment by lorenzwalthert** [comment]
Thanks. I don't think function declarations should be treated differently in this regard than other code.That is, it should be broken at 80 characters. We have #247, which I think should cover this case, however, as mentioned in https://github.com/r-lib/styler/issues/247#issuecomment-485481338, we'll probably start with function calls since they are the vast majority offending cases, and then maybe come back to the declaration case.
