### ISSUE TITLE
getting argument specifications starting on new line in the same line as the argument name

### ISSUE THREAD

**Issue by IndrajeetPatil** [r-lib/styler#734]
So, for example, I would have expected the following

``` r
styler::style_text(
  "mean( 
  x =
  c(2.62, 2.875, 2.32, 3.215, 3.44, 3.46),
    
      
      na.rm    = 
  TRUE)"
)
#> mean(
#>   x =
#>     c(2.62, 2.875, 2.32, 3.215, 3.44, 3.46),
#>   na.rm =
#>     TRUE
#> )
```

<sup>Created on 2021-02-19 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

to be styled as

```r
#> mean(
#>   x = c(2.62, 2.875, 2.32, 3.215, 3.44, 3.46),
#>   na.rm = TRUE
#> )
```

**Comment by lorenzwalthert** [comment]
Not sure. I think we wanted styler to be non-invasive. That's why we added an indention rule to indent after `=`. Depending on your code, you'll end up with quite long lines and it's unclear if you need to create another line break and if so, where, when you go from
```r
call(
  this_is(nested(3), x = 
    anotherprettylongcallthatis_not_ending(, 3)
))
```
to 
```r
call(
  this_is(nested(3), x = anotherprettylongcallthatis_not_ending(, 3)
))
```
So I think we best leave this as is.
