### ISSUE TITLE
lapply is not treated consistently

### ISSUE THREAD

**Issue by njtierney** [r-lib/styler#780]
Hi there! 

Thanks for creating and maintaining the styler pkg!

I've just noticed a couple of cases where the line breaks isn't consistent, and was wondering if there is an explanation or if it is a bug?

for example, [this `apply` has a new line for each argument](https://github.com/greta-dev/greta/pull/374/files#diff-c0e157588dbf781aba58998db2a27123bbcc9255fa84adc7d0a1f771a56893ffR680) but [this line has all the arguments on one line?](https://github.com/greta-dev/greta/pull/374/files#diff-2103f1643bc6bfca8c6f919de9e1d01c9e408bf28f9df5931852b58a1ea05cccR467)

I am using styler version 1.3.2

cheers!

**Comment by lorenzwalthert** [comment]
Hi 😊 

Sorry, but from the two links, I can't see exactly what you mean. Can you post a link with a line reference or a reprex here? In general, line breaks in function calls depend on whether or not arguments are named (see https://github.com/tidyverse/style/issues/39). If a call is multi-line and the first few arguments are unnamed, they can go on the first line, named arguments follow after a line break. If the first few arguments are named, the first line of the call does not contain arguments. Like this:

```r
map(x, f
  arg = 1
)

# vs
map(
  .x = x, 
  .f = f, 
  arg = 1
)
```

**Comment by lorenzwalthert** [comment]
Also, note that the latest styler version is `1.4.1`, which is one year younger than `1.3.2`, so I suggest using this one.

**Comment by njtierney** [comment]
Hi! 😄 

OK cool i've updated styler and am re-running it again now,

not sure why those links didn't work, here's the PR where we've referred to them inline.

https://github.com/greta-dev/greta/pull/374

I understand your example above

```r
map(x, f
  arg = 1
)

# vs
map(
  .x = x, 
  .f = f, 
  arg = 1
)
```

however what we are noting is something like:

```r
percentages <- function() {
  reads <- lapply(
    greta_stash$percentage_log_files,
    read_progress_log_file
  )
  render_progress(reads)
}

progress_bars <- function() {
  reads <- lapply(greta_stash$progress_bar_log_files,
    read_progress_log_file,
    skip = 1
  )
  render_progress(reads)
}
```

I guess one way forward might be to create our own style that always adds a new line, but I was just wondering why this is happening?

**Comment by lorenzwalthert** [comment]
Thanks. Let me put it differently: The general rule for multi-line function calls is to *always* break the line before the first argument *except* there are named arguments in the call. In that case, no line break is added before the first argument if there is none already. This is explained here: https://style.tidyverse.org/syntax.html#long-lines.  I try to explain what happened in your PR:

**Case one**

Multi-line function call without any named arguments.
```r
# input (https://github.com/greta-dev/greta/pull/374/files/472025f5d53e4ad2a58cf4423f01ca6c9f170397#r616413746)
reads <- lapply(greta_stash$percentage_log_files,
                read_progress_log_file)

# output
reads <- lapply(
  greta_stash$percentage_log_files,
  read_progress_log_file
)

```
Because no argument is named, styler ensures a line break before the first argument and before the closing brace.

**Case two**

Multi-line function call with at least one named argument.

```r
# input (https://github.com/greta-dev/greta/pull/374/files/472025f5d53e4ad2a58cf4423f01ca6c9f170397#r616414499)
lapply(greta_stash$progress_bar_log_files,
       read_progress_log_file,
       skip = 1)

# output with styler
lapply(greta_stash$progress_bar_log_files,
  read_progress_log_file,
  skip = 1
)
```
Because this call has named arguments (and they come after unnamed arguments), no line break is inserted before the first argument (`greta_stash$progress_bar_log_files`). If you remove `skip =`, you will see that the line is broken before the first argument (because you basically modify the example to be of *case one*).

How would you like this to be formatted? Yes, you can create your own style guide, but it comes with overhead...

**Comment by njtierney** [comment]
Thanks so much, @lorenzwalthert !  I think this all makes sense to me now.

I think we'll stick with the tidyverse style guide, perhaps in the future we might change something, but for the time being I think this encourages us to provide named arguments for most things where appropriate, and the style guide definitely helps us identify those places that need it, which is super helpful.

Thanks again! :)

**Comment by lorenzwalthert** [comment]
Cool. Glad you find styler useful and you can always come back if you need more support.
