### ISSUE TITLE
Support for styling .ipynb (IRKernel)

### ISSUE THREAD

**Issue by MichaelChirico** [r-lib/styler#807]
Would support for styling .ipynb files be in scope for `styler`? Ideally a flow like `styler::style_file('/path/to.ipynb')` which extracts the code chunks from the JSON & styles them, then writes back out in the correct JSON format.

**Comment by lorenzwalthert** [comment]
I consider this out of scope, mainly because other people already looked into this. E.g. you could use {styler} with the [jupyter lab formatter](https://jupyterlab-code-formatter.readthedocs.io/en/latest/installation.html#installation-step-2-installing-a-supported-code-formatter). Maybe we should add a note to the third-party adoption.

**Comment by grst** [comment]
You could also use [jupytext](https://github.com/mwouts/jupytext/) to save your jupyter notebooks as `Rmd` or plain `R` files and apply styler on them.

**Comment by MichaelChirico** [comment]
One reason not to outsource this to Jupyter front-end tooling is that .ipynb is a bit more general format then just Jupyter -- e.g. Colab uses roughly the same format, but it's not clear the same tooling will work interchangeably. Therefore I think it makes some sense for {styler} to own the logic, then the other downstreams can build on that.

Would you accept PR(s) for this? I might do so alongside a similar feature for {lintr}:

https://github.com/r-lib/lintr/issues/383

**Comment by lorenzwalthert** [comment]
Yes, I am open to reviewing a PR from you. Other advantage is that in pre-commit, we’ll be able to extend the styler-hook as well.
