### ISSUE TITLE
trailing comment within call breaks hanging indent

### ISSUE THREAD

**Issue by MichaelChirico** [r-lib/styler#813]
Compare the following:

```
writeLines(trimws('
list(
  a = 
    1,
  b = # comment here
    2
)'), tmp <- tempfile(fileext = '.R'))
styler::style_file(tmp)
writeLines(readLines(tmp))
# list(
#   a =
#     1,
#   b = # comment here
#   2
# )
```

It appears to be an issue inside calls; the following is unaffected:

```
a = 
  1
b = # comment here
  2
```

I confirmed this issue affects back to at least 1.1.0.

**Comment by lorenzwalthert** [comment]
I agree, thanks for reporting @MichaelChirico.

**Comment by MichaelChirico** [comment]
if you can point me to where I should be sniffing around I can have a go at filing a PR. I'm still a bit lost on the internals here & couldn't figure it out in 20 minutes or so

**Comment by lorenzwalthert** [comment]
Thanks so much for putting time in. I filed #814, which should resolve it. I think it's quite hard to understand the internals. Here's how I did it:

* knowing it's an indention rule -> `R/rules-indention.R `.
* knowing/checking which token it is related to: `EQ_SUB`

``` r
styler:::get_parse_data('c(x = #\n3)')
#> # A tibble: 10 x 11
#>    line1  col1 line2  col2    id parent token      terminal text    pos_id short
#>    <int> <int> <int> <int> <int>  <int> <chr>      <lgl>    <chr>    <int> <chr>
#>  1     1     1     2     2    14      0 expr       FALSE    "c(x =…      1 c(x =
#>  2     1     1     1     1     1      3 SYMBOL_FU… TRUE     "c"          2 c    
#>  3     1     1     1     1     3     14 expr       FALSE    "c"          3 c    
#>  4     1     2     1     2     2     14 '('        TRUE     "("          4 (    
#>  5     1     3     1     3     4     14 SYMBOL_SUB TRUE     "x"          5 x    
#>  6     1     5     1     5     5     14 EQ_SUB     TRUE     "="          6 =    
#>  7     1     7     1     7     6     14 COMMENT    TRUE     "#"          7 #    
#>  8     2     1     2     1     8      9 NUM_CONST  TRUE     "3"          8 3    
#>  9     2     1     2     1     9     14 expr       FALSE    "3"          9 3    
#> 10     2     2     2     2    10     14 ')'        TRUE     ")"         10 )
```

<sup>Created on 2021-06-25 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

* Putting a browser statement in `indent_eq_sub()` and play through the example.
* realise that for `= #\n`, not `#` but the next token that is not a comment should be indented.
* recalling that there is a function `next_non_comment()` to figure that out.
* looking for an `eq[-_]sub.*-in.R` file and adding our example. 
* run test to generate the `-out.R` file and check if that's what I wanted, commit, push.

For the future, I am happy to provide assistance if you want to resolve issues yourself instead of resolving myself directly. Please state that in the issue in the future in that case. I generally assume (maybe wrongly) that the reporters of bugs don't want/can't resolve them.

**Comment by MichaelChirico** [comment]
Happy to help when I can, but it will take some time to get the same instincts for debugging it seems.

Thanks for walking through your debug process!
