### ISSUE TITLE
pipe-newline-brace inside call becomes pipe-brace-newline, violating pipe_continuation_linter

### ISSUE THREAD

**Issue by MichaelChirico** [r-lib/styler#823]
```
writeLines('foo(
  data %>%
    filter(bar) %>%
    {
      cor(.$col1, .$col2, use = "complete.obs")
    }
)', tmp <- tempfile(fileext = '.R'))
# no output
lintr::lint(tmp, lintr::pipe_continuation_linter)
styler::style_file(tmp)
lintr::lint(tmp, lintr::pipe_continuation_linter)
# /tmp/RtmpvW85W0/file23c61b1a6b533a.R:3:19: style: `%>%` should always have a space before it...
#     filter(bar) %>% {
#                 ~~^
```

This didn't happen when I tried to remove the outer `foo()` call

**Comment by lorenzwalthert** [comment]
I see. Note that you combine two special cases here. 

1. use the pipe in a function call is generally not recommended IRC. 
2. piping into curly braces is also not standard.

**Comment by MichaelChirico** [comment]
agree & I didn't write the code myself :)

FWIW, the call piped into is print() which feels like a special case (is ending with %>% print() recommended instead?) & I'm not confident the way to avoid braces (i.e. I am not fluent enough with whether we can just use .)

if styler fixed either/both of the pipe usage issues I think that'd also be fine :)

**Comment by lorenzwalthert** [comment]
After weighting in different options, I dediced to leave things as is:

* The [tidyverse style guide](https://style.tidyverse.org/pipes.html#short-pipes): 

> Sometimes it’s useful to include a short pipe as an argument to a function in a longer pipe. Carefully consider whether the code is more readable with a short inline pipe (which doesn’t require a lookup elsewhere) or if it’s better to move the code outside the pipe and give it an evocative name.

These are all one line expressions:
```r
# Good
x %>%
  select(a, b, w) %>%
  left_join(y %>% select(a, b, v), by = c("a", "b"))

# Better
x_join <- x %>% select(a, b, w)
y_join <- y %>% select(a, b, v)
left_join(x_join, y_join, by = c("a", "b"))
```


* We generally don't touch line breaks around pipes within function calls after a discussion in https://github.com/r-lib/styler/pull/503 in the spirit of non-invasiveness. Otherwise, without introducing more special handling, we would turn 
```r
call(x %>% f())

# into
call(x %>% 
  f()
)
```
or similar. The rules for line breaks around curly braces are [already quite complicated](https://github.com/r-lib/styler/blob/master/R/rules-line-breaks.R#L41-L90) (maybe a refactor would be helpful anyways).

Hence, I kindly ask you to manually resolve this manually.


*** 
IIRC, `%>%` pipes into the first argument, unless you use `.` anywhere, it does not pipe into the first argument, but where you want it:

``` r
library(magrittr)
1 %>%
  c(2)
#> [1] 1 2

1 %>%
  c(2, .)
#> [1] 2 1

1 %>%
  c(2, ., .)
#> [1] 2 1 1
```

<sup>Created on 2021-07-15 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>
 

I think you should be able to do things like
```r
I(
  mtcars %>%
    dplyr::filter(hp < Inf) %>%
    cor(.$cyl, .$mph, use = "complete.obs")
)
```
or just move the pipe outside the function call.
```r
arg <- mtcars %>%
  dplyr::filter(hp < Inf) %>% 
  {
    cor(.$cyl, .$mph, use = "complete.obs")
  }
I(arg)
```


IMO ending with print can make sense in general yes, e.g. in function definitions or 
```r
invisible(3) %>%
  print()
```

**Comment by lorenzwalthert** [comment]
Anyways, re-considering, #825 would resolve it.
