### ISSUE TITLE
Multiline `@examplesIf`?

### ISSUE THREAD

**Issue by jonkeane** [r-lib/styler#826]
I'm noticing that long lines with the roxygen2 tag `@examplesIf` [get line wrapped with styler](https://github.com/r-lib/styler/blob/e7562f14801bb3886757913911fd54a0e674a80f/tests/testthat/roxygen-examples-complete/23-exampleIf-multiline-cond-out.R#L4-L7). Though my experience has been that roxygen2 doesn't actually support these right now (I've created https://github.com/r-lib/roxygen2/issues/1242 asking about adding that support).

If roxygen2 ends up supporting multi-line `@examplesIf` blocks, styler's current behavior is fine, but currently there appears to be a mismatch.

On another note: I've experienced some oddities when marking these lines as don't style / don't lint. If I do the following:

```
# nolint start
#' @examplesIf long_condition_line
# nolint end
```

And then style the file, the line `# nolint end` is deleted by styler.

If I do the following, everything is fine and the `#' # nolint end` file at the end is not removed:

```
# nolint start
#' @examplesIf long_condition_line
#' # nolint end
```

but that looks a bit funny to my eyes.

**Comment by lorenzwalthert** [comment]
Thanks @jonkeane for reporting.

> I'm noticing that long lines with the roxygen2 tag @examplesIf get line wrapped with styler. 

I am not sure I can follow. You mean behavior like this?

``` r
styler::style_text("
#' This
#'
#'
#' is stuff
#'
#' @examplesIf {TRUE }
#' 1
NULL
")
#> 
#> #' This
#> #'
#> #'
#> #' is stuff
#> #'
#> #' @examplesIf {
#> #'   TRUE
#> #' }
#> #' 1
#> NULL
```

<sup>Created on 2021-08-03 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

Also note that like {roxygen2}, styler only recognizes roxygen code examples if there is a non-comment block following the roxygen comment.

Regarding the deletion, can you please provide a [reprex](), because I can't make this happen: 

``` r
styler::style_text("
# nolint start
#' @examplesIf long_condition_line
# nolint end
")
#> 
#> # nolint start
#> #' @examplesIf long_condition_line
#> # nolint end
```

<sup>Created on 2021-08-03 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

Also not when adding `NULL` at the end.

**Comment by jonkeane** [comment]
Yes, AFAICT that behavior produces `@examplesIf` blocks that roxygen2 cannot parse and will error on. On r-lib/roxygen2#1242, a workaround was suggested to create an internal helper function which works fine for my purposes. But it would be good if styler output valid roxygen2 blocks there.

As for the tangential issue, this took a bit more pruning, but I finally got something more minimal. The two critical bits I needed to trigger it are: a `%>%` in the example and a function definition below. Without either of those I get behavior where the line is either kept as is or transformed into `#' # nolint end`.

---
author: jkeane
date: 2021-08-03
output: "reprex::reprex\\_document"
title: drear-kitty\_reprex.R
---

``` r
styler::style_text("
# nolint start
#' @examplesIf TRUE
# nolint end
#' df %>% func()
func <- function() NULL
")
#> 
#> # nolint start
#> #' @examplesIf TRUE
#> #' df %>% func()
#> func <- function() NULL
```

<sup>Created on 2021-08-03 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by lorenzwalthert** [comment]
* Multiline: My first idea was to remove the line-break scope from the `@examplesIf`. This does not work because the example itself and the if condition are styled in one go. We had to therefore first split these lines int two blocks and then style both separately. This would slow down styler.  Or only format the second block, but I don't like this idea neither. ANother solution is to wait if {roxygen} adds support in r-lib/roxygen2#1242. Or most pragmatic: Assume conditions are one-liners, format, check if result is also one-liner, if not, give an informative warning/error.

* line deleted: Ok, thanks for this, I'll have to look into this later.

**Comment by lorenzwalthert** [comment]
Yes, please open a new one.
