### ISSUE TITLE
Error using code from customizing vignette

### ISSUE THREAD

**Issue by maelle** [r-lib/styler#844]
``` r
code <- c("add_one <- function(x) { x + 1 }")

styler:::create_tree(code)
#> Error in text_to_flat_pd(text, transformers, more_specs = more_specs): l'argument "more_specs" est manquant, avec aucune valeur par défaut
```

<sup>Created on 2021-09-30 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by maelle** [comment]
I also get an error running `pd <- styler:::compute_parse_data_nested(code)` but this time complaining about `transformers`.

**Comment by lorenzwalthert** [comment]
As per this very vignette:

> Make sure to also disable caching during development with `cache_deactivate()`
because styling the same text with a different style guide that has the same
version and name will fool the cache invalidation in the case your style guide
has transformer functions with different function bodies. Make sure to increment
the version number of your style guide with every release. It should correspond
to the version of the package from which you export your style guide.

I did not want to add handling active cache during development because it cost/benefit is too small. Also, I think while this vignette sheds light on some aspects of developing a style guide, it's not complete enough (and even has some mental jumps IIRC) for package developers who want to create their own style guide. In particular, recently developed aspects such as caching, transformer dropping are insufficiently documented. The reason is that this documentation is only relevant for people who want to develop their own style guide, which I estimate to be < 5 (globally :D). So please ask if you have concrete questions. There is https://github.com/r-lib/styler/issues/721 to track this, which links to

**Comment by lorenzwalthert** [comment]
Also, I believe the best current example for a third-party style guide is https://github.com/mlr-org/styler.mlr

**Comment by lorenzwalthert** [comment]
@maelle if you want, you can have a look at #846 and provide feedback.

**Comment by maelle** [comment]
Thanks @lorenzwalthert! In the end, the slight tweak I wanted to make was done following your [blog post](https://lorenzwalthert.com/post/customizing-styler-the-quick-way/).

**Comment by maelle** [comment]
The link to the mlr styler is broken. :thinking:

**Comment by lorenzwalthert** [comment]
In the vignette in #846 or where?

**Comment by maelle** [comment]
In https://github.com/r-lib/styler/issues/844#issuecomment-932349315 and in the vignette in the PR #846. It's as if the package disappeared/became private.

**Comment by lorenzwalthert** [comment]
Oh yes, it's private, I asked to make it public.

**Comment by maelle** [comment]
Ah cool, mystery solved :grin: 

For info here's the package https://github.com/ropensci-review-tools/spaceout holding this style https://github.com/ropensci-review-tools/pkgcheck/blob/main/CONTRIBUTING.md#development-guidelines
