### ISSUE TITLE
allow tab indentation

### ISSUE THREAD

**Issue by jam1015** [r-lib/styler#874]
I know that the Tidyverse style guide likes tabs for some reason, but lots of people, including myself, don't. Tabs are nice because they just magically line everything up, and they help with visualization when they're displayed in the text editor.  I looked at the 'customizing styler' vignette but the contents were too complicated for a quick fix to allow autoformatting with tabs. I know this is an annoying request, bit I'd like a higher level styling tool that lets users easily pick what they want without getting too far down into the weeds. I recognize that I'm being a begger and chooser at the same time, but I just wanted to get this off my chest.

**Comment by lorenzwalthert** [comment]
This was previously requested: https://github.com/r-lib/styler/issues/347. It seems [quite easy to extend {styler} to use tabs instead of spaces](https://github.com/lorenzwalthert/styler/commit/110f4725eeb7323bc52671a2b1d16b1ce0720084) as the indent character. So maybe, we could introduce an argument in the style guide for it, although as with #347,  it sounded like trouble. @krlmlr what do you think about it? Alternative is to expose the argument in `create_style_guide()` only, so @jam1015 could create his own version of the tidyverse style guide (just c/p and change one argument) with the tabs version using [styler.yours](https://github.com/lorenzwalthert/styler.yours) and we don't have any maintenance responsibility.

**Comment by jam1015** [comment]
Thanks a lot for the response. Still learning R coding while going on tangents like this about tooling/formatting with tools like this rather than just an easy solution like Rstudio.  So the easy changes you made are not quite obvious to me but I hope that they will be with more study so I can be a contributor.  

In my vision ideal world, there would be an easier way to customize one's own R style guide.  An example of easy style customization that I think works well is the customization for [clang-format](https://clang.llvm.org/docs/ClangFormatStyleOptions.html). It is a well established tool that people who really know what they are doing use, but nevertheless someone who is not an expert can look at those options and make their own custom format specification fairly easily.

[This post](https://www.r-bloggers.com/2018/07/customizing-styler-the-quick-way/) agrees that [customizing `styler`](https://cran.r-project.org/web/packages/styler/vignettes/customizing_styler.html) is  deep dive for the novice.  [styler.yours](https://github.com/lorenzwalthert/styler.yours) could already be what I'm looking for, will dive more deeply into it when I have time!

**Comment by 875d** [comment]
so how you go about it?

Using tabs instead of spaces for indentation?

You create a new style guide?
