### ISSUE TITLE
the code is invalid, and report an error

### ISSUE THREAD

**Issue by xjtusjtu** [r-lib/styler#877]
![image](https://user-images.githubusercontent.com/57665402/146500571-c369a2f0-bf99-4bbb-9b40-9f2b0e71ab50.png)
Today there comes an error, and it can't work
it work properly before today
I don't know why
I uninstall Rstudio, and reinstall R, but it does not make a difference.
The error is still here

**Comment by lorenzwalthert** [comment]
Please see my comment on  [StackOverflow](https://stackoverflow.com/questions/70219634/styler-r-package-does-nothing#comment124163510_70219634). It's probably because you upgraded the {rstudioapi} package or similar that the output is different. It also only works in the embeeded R terminal, not if you open R in a `zsh` or similar within RStudio. If this does not help, more context would be useful to diagnose the problem.

**Comment by xjtusjtu** [comment]
Thank you very much! 
It works successfully in RStudio-Terminal, but it does not work in VScode terminal（previously it could work）. 
In addition, if I hope it could work successfully as before, what I should do or learn?

**Comment by lorenzwalthert** [comment]
Please see https://github.com/REditorSupport/vscode-R/issues/421.
There is this blog post on RStudio Addins and vs code: https://www.milesmcbain.com/posts/adding-addins-to-vscode/. Maybe this helps.

**Comment by xjtusjtu** [comment]
Thanks so much again！！

**Comment by xjtusjtu** [comment]
Bro, I know how to solve this problem, in the VScode plugin - ==R==, find the option `R>Session: Emulate RStudion API`, and check it. Then we can input `styler:::style_active_file()` in the VScode R terminal and it work properly and successfully.

Many thanks again for your help~

**Comment by lorenzwalthert** [comment]
Glad it works now.
