### ISSUE TITLE
custom nested parenthesis format possible?

### ISSUE THREAD

**Issue by ssh352** [r-lib/styler#896]
Hi, is it possible for a user to add customization to styler to get desiredFormat instead of stylerFormat in the code below?

https://gist.github.com/ssh352/26eaa9fc99a1dcee2ff50664bfef3c09

**Comment by ssh352** [comment]
<img width="779" alt="Screen Shot 2022-01-05 at 10 49 43 AM" src="https://user-images.githubusercontent.com/41779116/148153367-a3a79c77-22d2-477a-b1e4-b99fe1d5e8d1.png">

**Comment by lorenzwalthert** [comment]
Hi @ssh352. It is possible to customize {styler}, but you need to be able to formalize how you want styling to happen, e.g.

> Always break line after `mutate()` if multi-line.

There are vignettes on this for the dev version, which you find under https://styler.r-lib.org/dev/ -> Articles. Adapting or creating your own style guide is not straight-forward though, as these articles suggest.

In your specific case, I think nested `mutate()` statements are not a good idea from a style perspective. I'd try to capsule things a bit more, then the problem is solved also.

```r
library(dplyr)
library(tidyr)
library(purrr) # map
library(slider)

# only returns rsquared
get_coef1 <- function(data) {
  coef1 <- lm(data = data, r1 ~ r2 + r3) %>%
    coef() %>%
    .["r2"] %>%
    unname()

  return(coef1)
}

data <- tibble(
  t = rep(1:10, 3),
  case = c(rep("a", 10), rep("b", 10), rep("c", 10)),
  r1 = rnorm(30),
  r2 = rnorm(30),
  r3 = rnorm(30)
)

slid_coef <- function(data) {
  slider::slide_dbl(data, ~ get_coef1(.x),
    .before = Inf,
    .complete = TRUE
  )
}
add_coef <- function(data) {
  mutate(data, coef1 = slide_coef)
}
stylerFormat %>%
  group_by(case) %>%
  nest() %>%
  mutate(rollreg = map(data, add_coef)) %>%
  select(-data) %>%
  unnest(rollreg)

```

**Comment by ssh352** [comment]
Thank you! They key for me is readability. I find it hard to read when I can't visually match the opening and closing parenthesis. However the code you showed made it very readable. Thanks to StyleR and the authors.
