### ISSUE TITLE
Formula with comments can cause error

### ISSUE THREAD

**Issue by MichaelChirico** [r-lib/styler#899]
```
styler::style_text("
lm(
  log(y + 1) ~
    # sqrt(x1) +
    sqrt(x2) +
    # sqrt(x3) +
    x4 +
    sqrt(x5)
)
```

errors:

```
Error in if (any(is_plus_or_comment_after_plus_before_fun_call)) { : 
  missing value where TRUE/FALSE needed
```

I tried minimizing the example further, to no avail -- seems all of those parts are required to trigger the issue

**Comment by lorenzwalthert** [comment]
Thanks @MichaelChirico. If you go into the debugging mode, you can see that the error occurs in `set_linebreak_after_ggplot2_plus()`, the function that adds a line break after `+` in {ggplot2} calls.  `token_after` is only defined in the `pd` for terminals, otherwise it's `NA`. Hence, checking if the token after the plus is a function call or not gives non-missing only for terminals. Since we only want to change line breaks after `+`, which is a terminal, we can simply omit the missing values in `is_plus_or_comment_after_plus_before_fun_call`.

**Comment by MichaelChirico** [comment]
thanks for the fix & walk through!!
