### ISSUE TITLE
Spacing of hanging formulas?

### ISSUE THREAD

**Issue by MichaelChirico** [r-lib/styler#900]
Styler does something odd w.r.t. hanging formulas:

```
styler::style_text("
y ~
  x +
  y
")
```

```
y ~
x +
  y
```

I would expect `x` to have a higher indentation level than `y`. At least, nothing should be done here, since this isn't mentioned in the style guide IIUC.

**Comment by lorenzwalthert** [comment]
Thanks @MichaelChirico. Indeed, this was not intended. I just never had formulas longer than one line 😄. The reason for this is simply that `~` is not listed as a token to create indention. In addition, because of the parse table structure, we also need to list it as a token that gets flattened out, otherwise, we'll end up with too much indention.
```r
y ~ 
  x + 
    w
```

**Comment by MichaelChirico** [comment]
personally I could go either way on whether the 3rd line should be indented further. might be worth raising this upstream for clarity.

**Comment by lorenzwalthert** [comment]
You could do that, but I doubt Hadley cares about it, because it's a very rare case. Given that it has not come up in 4 years of {styler}, I think we can decide it here (and if someone complains, adapt). Both options are better than the status quo. If you feel strongly, you can file it upstream, otherwise I will merge it towards the end of the month. Ok?

**Comment by MichaelChirico** [comment]
I'm not sure it's so rare... we've got over 1,000 instances of >1-line formulae in hundreds of different scripts (should be even more prevalent in the Rmds and ipynb).

Agreed it's better than status quo. I'm also not sure what to expect in general, e.g. when the LHS is very long too:

```
y_variable_1 + y_variable_2 + 
  y_variable_3 ~
  x_variable_1 + x_variable_2 + x_variable_3 +
  x_variable_4
```

looks odd... how about at least ensuring that the RHS gets an extra indent w.r.t. the LHS? that's probably the most important distinction.

**Comment by lorenzwalthert** [comment]
> looks odd... how about at least ensuring that the RHS gets an extra indent w.r.t. the LHS? that's probably the most important distinction.

Can you explicitly show how you want the code to look like then?

**Comment by MichaelChirico** [comment]
```
y_variable_1 + y_variable_2 + 
  y_variable_3 ~
    x_variable_1 + x_variable_2 + x_variable_3 +
    x_variable_4
```

**Comment by lorenzwalthert** [comment]
FWIW, RStudio does not add another level of indention on line 3, so typing yields:
```r
y_variable_1 + y_variable_2 + 
  y_variable_3 ~
  x_variable_1 + x_variable_2 + x_variable_3 +
  x_variable_4
```
Maybe we should just do that?

**Comment by MichaelChirico** [comment]
Works for me -- still an improvement in any case.
