### ISSUE TITLE
Styling of R6 Classes feels a little slow 

### ISSUE THREAD

**Issue by sebffischer** [r-lib/styler#942]
I am not sure exactly how styler works but I think the styling of R6 classes could be sped up and feels a little slow sometimes. I guess the problem is that it all happens in one big `R6(...)` function call, causing styler to restyle the whole R6 class each time it is formatted. Maybe caching could be somehow be improved here?

**Comment by lorenzwalthert** [comment]
Caching happens on two levels as explained in the [vignette](https://styler.r-lib.org/articles/caching.html). I agree that it migth be slow for very big objects for that reason. R6 classes might be a good starting point for optimizing, but I think this issue is fundamentally #558, so I suggest to close it as a duplicate.
