### ISSUE TITLE
Document the styling UI in a single `.Rd` file?

### ISSUE THREAD

**Issue by IndrajeetPatil** [r-lib/styler#971]
Currently, these functions are [separately documented](https://styler.r-lib.org/reference/index.html) and there is a lot of duplication of the content.

<img width="962" alt="Screenshot 2022-07-29 at 14 54 04" src="https://user-images.githubusercontent.com/11330453/181765296-e35fbf74-0e65-457f-8530-63cdc20e230c.png">

Instead, we could do this the same way `{lintr}` does it; cataloguing them [in a single place](https://lintr.r-lib.org/reference/lint.html).

<img width="875" alt="Screenshot 2022-07-29 at 14 54 32" src="https://user-images.githubusercontent.com/11330453/181765440-98356ab0-c9d0-439d-b288-f506a01e58fa.png">

If you agree, I can make a PR.

**Comment by lorenzwalthert** [comment]
I do see there is a lot of duplication. Mostly kn the user side though. At source, there is very little due to inheritance and smart use of roxygen. I think addin and text are distinct from the file formatters so my suggestion is to merge file, dir, and package and then see what to do with text. Some sections from some of the help files are also applicable to other docs, so maybe we could also make sure that’s consistent. I’d appreciate a PR.

**Comment by IndrajeetPatil** [comment]
Not planned. See https://github.com/r-lib/styler/pull/972#issuecomment-1214142705.
